# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\edupt\Documents\GitHub\GroupQuiz\UI\Version 2\lighting_control.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import os
SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1032, 640)
        MainWindow.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_channels = QtWidgets.QFrame(self.centralwidget)
        self.frame_channels.setGeometry(QtCore.QRect(10, 60, 491, 261))
        self.frame_channels.setStyleSheet("background-color: rgba(105, 105, 105, 120);\n"
"border-color: rgb(255, 255, 255);")
        self.frame_channels.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_channels.setObjectName("frame_channels")
        self.verticalSlider_a_1 = QtWidgets.QSlider(self.frame_channels)
        self.verticalSlider_a_1.setGeometry(QtCore.QRect(10, 40, 32, 169))
        self.verticalSlider_a_1.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.verticalSlider_a_1.setMaximum(127)
        self.verticalSlider_a_1.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_1.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_1.setTickInterval(8)
        self.verticalSlider_a_1.setProperty("selected", False)
        self.verticalSlider_a_1.setObjectName("verticalSlider_a_1")
        self.verticalSlider_a_2 = QtWidgets.QSlider(self.frame_channels)
        self.verticalSlider_a_2.setGeometry(QtCore.QRect(50, 40, 32, 169))
        self.verticalSlider_a_2.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.verticalSlider_a_2.setMaximum(127)
        self.verticalSlider_a_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_2.setTickInterval(8)
        self.verticalSlider_a_2.setProperty("selected", False)
        self.verticalSlider_a_2.setObjectName("verticalSlider_a_2")
        self.verticalSlider_a_3 = QtWidgets.QSlider(self.frame_channels)
        self.verticalSlider_a_3.setGeometry(QtCore.QRect(90, 40, 32, 169))
        self.verticalSlider_a_3.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.verticalSlider_a_3.setMaximum(127)
        self.verticalSlider_a_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_3.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_3.setTickInterval(8)
        self.verticalSlider_a_3.setProperty("selected", False)
        self.verticalSlider_a_3.setObjectName("verticalSlider_a_3")
        self.verticalSlider_a_4 = QtWidgets.QSlider(self.frame_channels)
        self.verticalSlider_a_4.setGeometry(QtCore.QRect(130, 40, 32, 169))
        self.verticalSlider_a_4.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.verticalSlider_a_4.setMaximum(127)
        self.verticalSlider_a_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_4.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_4.setTickInterval(8)
        self.verticalSlider_a_4.setProperty("selected", False)
        self.verticalSlider_a_4.setObjectName("verticalSlider_a_4")
        self.verticalSlider_a_5 = QtWidgets.QSlider(self.frame_channels)
        self.verticalSlider_a_5.setGeometry(QtCore.QRect(170, 40, 32, 169))
        self.verticalSlider_a_5.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.verticalSlider_a_5.setMaximum(127)
        self.verticalSlider_a_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_5.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_5.setTickInterval(8)
        self.verticalSlider_a_5.setProperty("selected", False)
        self.verticalSlider_a_5.setObjectName("verticalSlider_a_5")
        self.verticalSlider_a_6 = QtWidgets.QSlider(self.frame_channels)
        self.verticalSlider_a_6.setGeometry(QtCore.QRect(210, 40, 32, 169))
        self.verticalSlider_a_6.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.verticalSlider_a_6.setMaximum(127)
        self.verticalSlider_a_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_6.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_6.setTickInterval(8)
        self.verticalSlider_a_6.setProperty("selected", False)
        self.verticalSlider_a_6.setObjectName("verticalSlider_a_6")
        self.verticalSlider_a_7 = QtWidgets.QSlider(self.frame_channels)
        self.verticalSlider_a_7.setGeometry(QtCore.QRect(250, 40, 32, 169))
        self.verticalSlider_a_7.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.verticalSlider_a_7.setMaximum(127)
        self.verticalSlider_a_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_7.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_7.setTickInterval(8)
        self.verticalSlider_a_7.setProperty("selected", False)
        self.verticalSlider_a_7.setObjectName("verticalSlider_a_7")
        self.verticalSlider_a_8 = QtWidgets.QSlider(self.frame_channels)
        self.verticalSlider_a_8.setGeometry(QtCore.QRect(290, 40, 32, 169))
        self.verticalSlider_a_8.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.verticalSlider_a_8.setMaximum(127)
        self.verticalSlider_a_8.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_8.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_8.setTickInterval(8)
        self.verticalSlider_a_8.setProperty("selected", False)
        self.verticalSlider_a_8.setObjectName("verticalSlider_a_8")
        self.verticalSlider_a_9 = QtWidgets.QSlider(self.frame_channels)
        self.verticalSlider_a_9.setGeometry(QtCore.QRect(330, 40, 32, 169))
        self.verticalSlider_a_9.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.verticalSlider_a_9.setMaximum(127)
        self.verticalSlider_a_9.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_9.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_9.setTickInterval(8)
        self.verticalSlider_a_9.setProperty("selected", False)
        self.verticalSlider_a_9.setObjectName("verticalSlider_a_9")
        self.verticalSlider_a_10 = QtWidgets.QSlider(self.frame_channels)
        self.verticalSlider_a_10.setGeometry(QtCore.QRect(370, 40, 32, 169))
        self.verticalSlider_a_10.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.verticalSlider_a_10.setMaximum(127)
        self.verticalSlider_a_10.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_10.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_10.setTickInterval(8)
        self.verticalSlider_a_10.setProperty("selected", False)
        self.verticalSlider_a_10.setObjectName("verticalSlider_a_10")
        self.verticalSlider_a_11 = QtWidgets.QSlider(self.frame_channels)
        self.verticalSlider_a_11.setGeometry(QtCore.QRect(410, 40, 32, 169))
        self.verticalSlider_a_11.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.verticalSlider_a_11.setMaximum(127)
        self.verticalSlider_a_11.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_11.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_11.setTickInterval(8)
        self.verticalSlider_a_11.setProperty("selected", False)
        self.verticalSlider_a_11.setObjectName("verticalSlider_a_11")
        self.verticalSlider_a_12 = QtWidgets.QSlider(self.frame_channels)
        self.verticalSlider_a_12.setGeometry(QtCore.QRect(450, 40, 32, 169))
        self.verticalSlider_a_12.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.verticalSlider_a_12.setMaximum(127)
        self.verticalSlider_a_12.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_12.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_12.setTickInterval(8)
        self.verticalSlider_a_12.setProperty("selected", False)
        self.verticalSlider_a_12.setObjectName("verticalSlider_a_12")
        self.label_a_1 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_1.setGeometry(QtCore.QRect(10, 10, 32, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_1.setFont(font)
        self.label_a_1.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_a_1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_1.setObjectName("label_a_1")
        self.label_a_2 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_2.setGeometry(QtCore.QRect(50, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_2.setFont(font)
        self.label_a_2.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_a_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_2.setObjectName("label_a_2")
        self.label_a_3 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_3.setGeometry(QtCore.QRect(90, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_3.setFont(font)
        self.label_a_3.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_a_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_3.setObjectName("label_a_3")
        self.label_a_4 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_4.setGeometry(QtCore.QRect(130, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_4.setFont(font)
        self.label_a_4.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_a_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_4.setObjectName("label_a_4")
        self.label_a_5 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_5.setGeometry(QtCore.QRect(170, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_5.setFont(font)
        self.label_a_5.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_a_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_5.setObjectName("label_a_5")
        self.label_a_6 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_6.setGeometry(QtCore.QRect(210, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_6.setFont(font)
        self.label_a_6.setStyleSheet("\n"
"color: rgb(0, 0, 0);background-color: rgba(0, 0, 0, 0);")
        self.label_a_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_6.setObjectName("label_a_6")
        self.label_a_7 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_7.setGeometry(QtCore.QRect(250, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_7.setFont(font)
        self.label_a_7.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_a_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_7.setObjectName("label_a_7")
        self.label_a_8 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_8.setGeometry(QtCore.QRect(290, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_8.setFont(font)
        self.label_a_8.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_a_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_8.setObjectName("label_a_8")
        self.label_a_9 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_9.setGeometry(QtCore.QRect(330, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_9.setFont(font)
        self.label_a_9.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_a_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_9.setObjectName("label_a_9")
        self.label_a_10 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_10.setGeometry(QtCore.QRect(370, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_10.setFont(font)
        self.label_a_10.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_a_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_10.setObjectName("label_a_10")
        self.label_a_11 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_11.setGeometry(QtCore.QRect(410, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_11.setFont(font)
        self.label_a_11.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_a_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_11.setObjectName("label_a_11")
        self.label_a_12 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_12.setGeometry(QtCore.QRect(450, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_12.setFont(font)
        self.label_a_12.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_a_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_12.setObjectName("label_a_12")
        self.label_a_value_1 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_value_1.setGeometry(QtCore.QRect(10, 210, 32, 21))
        self.label_a_value_1.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_a_value_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_1.setObjectName("label_a_value_1")
        self.label_a_value_2 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_value_2.setGeometry(QtCore.QRect(50, 210, 32, 21))
        self.label_a_value_2.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_a_value_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_2.setObjectName("label_a_value_2")
        self.label_a_value_3 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_value_3.setGeometry(QtCore.QRect(90, 210, 32, 21))
        self.label_a_value_3.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_a_value_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_3.setObjectName("label_a_value_3")
        self.label_a_value_4 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_value_4.setGeometry(QtCore.QRect(130, 210, 32, 21))
        self.label_a_value_4.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_a_value_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_4.setObjectName("label_a_value_4")
        self.label_a_value_5 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_value_5.setGeometry(QtCore.QRect(170, 210, 32, 21))
        self.label_a_value_5.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_a_value_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_5.setObjectName("label_a_value_5")
        self.label_a_value_6 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_value_6.setGeometry(QtCore.QRect(210, 210, 32, 21))
        self.label_a_value_6.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_a_value_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_6.setObjectName("label_a_value_6")
        self.label_a_value_7 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_value_7.setGeometry(QtCore.QRect(250, 210, 32, 21))
        self.label_a_value_7.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_a_value_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_7.setObjectName("label_a_value_7")
        self.label_a_value_8 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_value_8.setGeometry(QtCore.QRect(290, 210, 32, 21))
        self.label_a_value_8.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_a_value_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_8.setObjectName("label_a_value_8")
        self.label_a_value_9 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_value_9.setGeometry(QtCore.QRect(330, 210, 32, 21))
        self.label_a_value_9.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_a_value_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_9.setObjectName("label_a_value_9")
        self.label_a_value_10 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_value_10.setGeometry(QtCore.QRect(370, 210, 32, 21))
        self.label_a_value_10.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_a_value_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_10.setObjectName("label_a_value_10")
        self.label_a_value_11 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_value_11.setGeometry(QtCore.QRect(410, 210, 32, 21))
        self.label_a_value_11.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_a_value_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_11.setObjectName("label_a_value_11")
        self.label_a_value_12 = QtWidgets.QLabel(self.frame_channels)
        self.label_a_value_12.setGeometry(QtCore.QRect(450, 210, 32, 21))
        self.label_a_value_12.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_a_value_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_12.setObjectName("label_a_value_12")
        self.checkBox_a_1 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_a_1.setGeometry(QtCore.QRect(20, 230, 16, 21))
        self.checkBox_a_1.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.checkBox_a_1.setText("")
        self.checkBox_a_1.setObjectName("checkBox_a_1")
        self.checkBox_a_2 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_a_2.setGeometry(QtCore.QRect(60, 230, 31, 21))
        self.checkBox_a_2.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.checkBox_a_2.setText("")
        self.checkBox_a_2.setObjectName("checkBox_a_2")
        self.checkBox_a_3 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_a_3.setGeometry(QtCore.QRect(100, 230, 31, 21))
        self.checkBox_a_3.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.checkBox_a_3.setText("")
        self.checkBox_a_3.setObjectName("checkBox_a_3")
        self.checkBox_a_4 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_a_4.setGeometry(QtCore.QRect(140, 230, 31, 21))
        self.checkBox_a_4.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.checkBox_a_4.setText("")
        self.checkBox_a_4.setObjectName("checkBox_a_4")
        self.checkBox_a_5 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_a_5.setGeometry(QtCore.QRect(180, 230, 31, 21))
        self.checkBox_a_5.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.checkBox_a_5.setText("")
        self.checkBox_a_5.setObjectName("checkBox_a_5")
        self.checkBox_a_6 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_a_6.setGeometry(QtCore.QRect(220, 230, 31, 21))
        self.checkBox_a_6.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.checkBox_a_6.setText("")
        self.checkBox_a_6.setObjectName("checkBox_a_6")
        self.checkBox_a_7 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_a_7.setGeometry(QtCore.QRect(260, 230, 31, 21))
        self.checkBox_a_7.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.checkBox_a_7.setText("")
        self.checkBox_a_7.setObjectName("checkBox_a_7")
        self.checkBox_a_8 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_a_8.setGeometry(QtCore.QRect(300, 230, 31, 21))
        self.checkBox_a_8.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.checkBox_a_8.setText("")
        self.checkBox_a_8.setObjectName("checkBox_a_8")
        self.checkBox_a_9 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_a_9.setGeometry(QtCore.QRect(340, 230, 31, 21))
        self.checkBox_a_9.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.checkBox_a_9.setText("")
        self.checkBox_a_9.setObjectName("checkBox_a_9")
        self.checkBox_a_10 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_a_10.setGeometry(QtCore.QRect(380, 230, 31, 21))
        self.checkBox_a_10.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.checkBox_a_10.setText("")
        self.checkBox_a_10.setObjectName("checkBox_a_10")
        self.checkBox_a_11 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_a_11.setGeometry(QtCore.QRect(420, 230, 31, 21))
        self.checkBox_a_11.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.checkBox_a_11.setText("")
        self.checkBox_a_11.setObjectName("checkBox_a_11")
        self.checkBox_a_12 = QtWidgets.QCheckBox(self.frame_channels)
        self.checkBox_a_12.setGeometry(QtCore.QRect(460, 230, 21, 21))
        self.checkBox_a_12.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.checkBox_a_12.setText("")
        self.checkBox_a_12.setObjectName("checkBox_a_12")
        self.verticalSlider_a_1.raise_()
        self.verticalSlider_a_2.raise_()
        self.verticalSlider_a_3.raise_()
        self.verticalSlider_a_4.raise_()
        self.verticalSlider_a_5.raise_()
        self.verticalSlider_a_6.raise_()
        self.verticalSlider_a_7.raise_()
        self.verticalSlider_a_8.raise_()
        self.verticalSlider_a_9.raise_()
        self.verticalSlider_a_10.raise_()
        self.verticalSlider_a_11.raise_()
        self.verticalSlider_a_12.raise_()
        self.label_a_1.raise_()
        self.label_a_2.raise_()
        self.label_a_3.raise_()
        self.label_a_4.raise_()
        self.label_a_5.raise_()
        self.label_a_6.raise_()
        self.label_a_7.raise_()
        self.label_a_8.raise_()
        self.label_a_9.raise_()
        self.label_a_10.raise_()
        self.label_a_11.raise_()
        self.label_a_12.raise_()
        self.label_a_value_1.raise_()
        self.label_a_value_2.raise_()
        self.label_a_value_3.raise_()
        self.label_a_value_4.raise_()
        self.label_a_value_5.raise_()
        self.label_a_value_6.raise_()
        self.label_a_value_7.raise_()
        self.label_a_value_8.raise_()
        self.label_a_value_9.raise_()
        self.label_a_value_10.raise_()
        self.label_a_value_11.raise_()
        self.label_a_value_12.raise_()
        self.checkBox_a_1.raise_()
        self.checkBox_a_2.raise_()
        self.checkBox_a_3.raise_()
        self.checkBox_a_4.raise_()
        self.checkBox_a_5.raise_()
        self.checkBox_a_6.raise_()
        self.checkBox_a_7.raise_()
        self.checkBox_a_8.raise_()
        self.checkBox_a_9.raise_()
        self.checkBox_a_10.raise_()
        self.checkBox_a_11.raise_()
        self.checkBox_a_12.raise_()
        self.frame_channelproperties = QtWidgets.QFrame(self.centralwidget)
        self.frame_channelproperties.setGeometry(QtCore.QRect(10, 410, 491, 181))
        self.frame_channelproperties.setStyleSheet("background-color: rgba(205, 205, 205, 120);")
        self.frame_channelproperties.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_channelproperties.setObjectName("frame_channelproperties")
        self.stackedWidget_channelproperties = QtWidgets.QStackedWidget(self.frame_channelproperties)
        self.stackedWidget_channelproperties.setGeometry(QtCore.QRect(10, 10, 471, 161))
        self.stackedWidget_channelproperties.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.stackedWidget_channelproperties.setObjectName("stackedWidget_channelproperties")
        self.page_noneselected = QtWidgets.QWidget()
        self.page_noneselected.setObjectName("page_noneselected")
        self.frame_noneselected = QtWidgets.QFrame(self.page_noneselected)
        self.frame_noneselected.setGeometry(QtCore.QRect(0, 0, 471, 161))
        self.frame_noneselected.setStyleSheet("background-color: rgba(15, 15, 20, 200);")
        self.frame_noneselected.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_noneselected.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_noneselected.setObjectName("frame_noneselected")
        self.label_noneselected = QtWidgets.QLabel(self.frame_noneselected)
        self.label_noneselected.setGeometry(QtCore.QRect(0, 0, 471, 161))
        self.label_noneselected.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_noneselected.setAlignment(QtCore.Qt.AlignCenter)
        self.label_noneselected.setObjectName("label_noneselected")
        self.stackedWidget_channelproperties.addWidget(self.page_noneselected)
        self.page_channeledit = QtWidgets.QWidget()
        self.page_channeledit.setObjectName("page_channeledit")
        self.frame_channeledit = QtWidgets.QFrame(self.page_channeledit)
        self.frame_channeledit.setGeometry(QtCore.QRect(0, 0, 471, 161))
        self.frame_channeledit.setStyleSheet("background-color: rgba(15, 15, 20, 200);")
        self.frame_channeledit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_channeledit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_channeledit.setObjectName("frame_channeledit")
        self.pushButton_lightcolor = QtWidgets.QPushButton(self.frame_channeledit)
        self.pushButton_lightcolor.setGeometry(QtCore.QRect(10, 40, 141, 23))
        self.pushButton_lightcolor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_lightcolor.setText("")
        self.pushButton_lightcolor.setFlat(False)
        self.pushButton_lightcolor.setObjectName("pushButton_lightcolor")
        self.label_ce_channelname = QtWidgets.QLabel(self.frame_channeledit)
        self.label_ce_channelname.setGeometry(QtCore.QRect(160, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_ce_channelname.setFont(font)
        self.label_ce_channelname.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_ce_channelname.setObjectName("label_ce_channelname")
        self.lineEdit_channelname = QtWidgets.QLineEdit(self.frame_channeledit)
        self.lineEdit_channelname.setGeometry(QtCore.QRect(10, 10, 141, 21))
        self.lineEdit_channelname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_channelname.setObjectName("lineEdit_channelname")
        self.label_ce_channelcol = QtWidgets.QLabel(self.frame_channeledit)
        self.label_ce_channelcol.setGeometry(QtCore.QRect(160, 40, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_ce_channelcol.setFont(font)
        self.label_ce_channelcol.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_ce_channelcol.setObjectName("label_ce_channelcol")
        self.spinBox = QtWidgets.QSpinBox(self.frame_channeledit)
        self.spinBox.setGeometry(QtCore.QRect(10, 70, 141, 22))
        self.spinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox.setMaximum(127)
        self.spinBox.setObjectName("spinBox")
        self.label_ce_currentval = QtWidgets.QLabel(self.frame_channeledit)
        self.label_ce_currentval.setGeometry(QtCore.QRect(160, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_ce_currentval.setFont(font)
        self.label_ce_currentval.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_ce_currentval.setObjectName("label_ce_currentval")
        self.plainTextEdit_notes = QtWidgets.QPlainTextEdit(self.frame_channeledit)
        self.plainTextEdit_notes.setGeometry(QtCore.QRect(10, 100, 451, 51))
        self.plainTextEdit_notes.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_notes.setObjectName("plainTextEdit_notes")
        self.stackedWidget_channelproperties.addWidget(self.page_channeledit)
        self.page_multiedit = QtWidgets.QWidget()
        self.page_multiedit.setObjectName("page_multiedit")
        self.frame_multiedit = QtWidgets.QFrame(self.page_multiedit)
        self.frame_multiedit.setGeometry(QtCore.QRect(0, 0, 471, 161))
        self.frame_multiedit.setStyleSheet("background-color: rgba(15, 15, 20, 200);")
        self.frame_multiedit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_multiedit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_multiedit.setObjectName("frame_multiedit")
        self.label_noneselected_2 = QtWidgets.QLabel(self.frame_multiedit)
        self.label_noneselected_2.setGeometry(QtCore.QRect(0, 0, 471, 41))
        self.label_noneselected_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_noneselected_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_noneselected_2.setObjectName("label_noneselected_2")
        self.verticalSlider_multiedit = QtWidgets.QSlider(self.frame_multiedit)
        self.verticalSlider_multiedit.setGeometry(QtCore.QRect(20, 40, 431, 31))
        self.verticalSlider_multiedit.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.verticalSlider_multiedit.setMaximum(127)
        self.verticalSlider_multiedit.setOrientation(QtCore.Qt.Horizontal)
        self.verticalSlider_multiedit.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_multiedit.setTickInterval(8)
        self.verticalSlider_multiedit.setObjectName("verticalSlider_multiedit")
        self.pushButton_fullup = QtWidgets.QPushButton(self.frame_multiedit)
        self.pushButton_fullup.setGeometry(QtCore.QRect(20, 80, 31, 31))
        self.pushButton_fullup.setText("")
        self.pushButton_fullup.setObjectName("pushButton_fullup")
        self.pushButton_fulldown = QtWidgets.QPushButton(self.frame_multiedit)
        self.pushButton_fulldown.setGeometry(QtCore.QRect(20, 120, 31, 31))
        self.pushButton_fulldown.setText("")
        self.pushButton_fulldown.setObjectName("pushButton_fulldown")
        self.label_me_100 = QtWidgets.QLabel(self.frame_multiedit)
        self.label_me_100.setGeometry(QtCore.QRect(60, 80, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_me_100.setFont(font)
        self.label_me_100.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_me_100.setObjectName("label_me_100")
        self.label_me_0 = QtWidgets.QLabel(self.frame_multiedit)
        self.label_me_0.setGeometry(QtCore.QRect(60, 120, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_me_0.setFont(font)
        self.label_me_0.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_me_0.setObjectName("label_me_0")
        self.stackedWidget_channelproperties.addWidget(self.page_multiedit)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 330, 491, 71))
        self.frame_3.setStyleSheet("background-color: rgba(205, 205, 205, 120);\n"
"border-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_flash_1 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_flash_1.setGeometry(QtCore.QRect(10, 10, 32, 51))
        self.pushButton_flash_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/lightning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_flash_1.setIcon(icon)
        self.pushButton_flash_1.setObjectName("pushButton_flash_1")
        self.pushButton_flash_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_flash_2.setGeometry(QtCore.QRect(50, 10, 32, 51))
        self.pushButton_flash_2.setText("")
        self.pushButton_flash_2.setIcon(icon)
        self.pushButton_flash_2.setObjectName("pushButton_flash_2")
        self.pushButton_flash_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_flash_3.setGeometry(QtCore.QRect(90, 10, 32, 51))
        self.pushButton_flash_3.setText("")
        self.pushButton_flash_3.setIcon(icon)
        self.pushButton_flash_3.setObjectName("pushButton_flash_3")
        self.pushButton_flash_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_flash_4.setGeometry(QtCore.QRect(130, 10, 32, 51))
        self.pushButton_flash_4.setText("")
        self.pushButton_flash_4.setIcon(icon)
        self.pushButton_flash_4.setObjectName("pushButton_flash_4")
        self.pushButton_flash_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_flash_5.setGeometry(QtCore.QRect(170, 10, 32, 51))
        self.pushButton_flash_5.setText("")
        self.pushButton_flash_5.setIcon(icon)
        self.pushButton_flash_5.setObjectName("pushButton_flash_5")
        self.pushButton_flash_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_flash_6.setGeometry(QtCore.QRect(210, 10, 32, 51))
        self.pushButton_flash_6.setText("")
        self.pushButton_flash_6.setIcon(icon)
        self.pushButton_flash_6.setObjectName("pushButton_flash_6")
        self.pushButton_flash_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_flash_7.setGeometry(QtCore.QRect(250, 10, 32, 51))
        self.pushButton_flash_7.setText("")
        self.pushButton_flash_7.setIcon(icon)
        self.pushButton_flash_7.setObjectName("pushButton_flash_7")
        self.pushButton_flash_8 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_flash_8.setGeometry(QtCore.QRect(290, 10, 32, 51))
        self.pushButton_flash_8.setText("")
        self.pushButton_flash_8.setIcon(icon)
        self.pushButton_flash_8.setObjectName("pushButton_flash_8")
        self.pushButton_flash_9 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_flash_9.setGeometry(QtCore.QRect(330, 10, 32, 51))
        self.pushButton_flash_9.setText("")
        self.pushButton_flash_9.setIcon(icon)
        self.pushButton_flash_9.setObjectName("pushButton_flash_9")
        self.pushButton_flash_10 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_flash_10.setGeometry(QtCore.QRect(370, 10, 32, 51))
        self.pushButton_flash_10.setText("")
        self.pushButton_flash_10.setIcon(icon)
        self.pushButton_flash_10.setObjectName("pushButton_flash_10")
        self.pushButton_flash_11 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_flash_11.setGeometry(QtCore.QRect(410, 10, 32, 51))
        self.pushButton_flash_11.setText("")
        self.pushButton_flash_11.setIcon(icon)
        self.pushButton_flash_11.setObjectName("pushButton_flash_11")
        self.pushButton_flash_12 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_flash_12.setGeometry(QtCore.QRect(450, 10, 32, 51))
        self.pushButton_flash_12.setText("")
        self.pushButton_flash_12.setIcon(icon)
        self.pushButton_flash_12.setObjectName("pushButton_flash_12")
        self.frame_sequencer = QtWidgets.QFrame(self.centralwidget)
        self.frame_sequencer.setGeometry(QtCore.QRect(510, 60, 511, 341))
        self.frame_sequencer.setStyleSheet("background-color: rgba(205, 205, 205, 120);\n"
"border-color: rgb(255, 255, 255);")
        self.frame_sequencer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_sequencer.setObjectName("frame_sequencer")
        self.pushButton_addStep = QtWidgets.QPushButton(self.frame_sequencer)
        self.pushButton_addStep.setGeometry(QtCore.QRect(10, 110, 31, 31))
        self.pushButton_addStep.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/plus-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_addStep.setIcon(icon1)
        self.pushButton_addStep.setObjectName("pushButton_addStep")
        self.pushButton_deleteStep = QtWidgets.QPushButton(self.frame_sequencer)
        self.pushButton_deleteStep.setGeometry(QtCore.QRect(90, 110, 31, 31))
        self.pushButton_deleteStep.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/cross-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_deleteStep.setIcon(icon2)
        self.pushButton_deleteStep.setObjectName("pushButton_deleteStep")
        self.widget = QtWidgets.QWidget(self.frame_sequencer)
        self.widget.setGeometry(QtCore.QRect(10, 150, 491, 131))
        self.widget.setStyleSheet("background-color: rgba(15, 15, 20, 200);")
        self.widget.setObjectName("widget")
        self.doubleSpinBox_fadetime = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_fadetime.setGeometry(QtCore.QRect(10, 10, 62, 22))
        self.doubleSpinBox_fadetime.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_fadetime.setDecimals(1)
        self.doubleSpinBox_fadetime.setMinimum(0.0)
        self.doubleSpinBox_fadetime.setObjectName("doubleSpinBox_fadetime")
        self.label_s_xfade = QtWidgets.QLabel(self.widget)
        self.label_s_xfade.setGeometry(QtCore.QRect(80, 10, 22, 22))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_s_xfade.setFont(font)
        self.label_s_xfade.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_s_xfade.setText("")
        self.label_s_xfade.setPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/arrow-transition.png"))
        self.label_s_xfade.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_s_xfade.setObjectName("label_s_xfade")
        self.doubleSpinBox_holdtime = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_holdtime.setGeometry(QtCore.QRect(10, 40, 62, 22))
        self.doubleSpinBox_holdtime.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_holdtime.setDecimals(1)
        self.doubleSpinBox_holdtime.setMinimum(0.0)
        self.doubleSpinBox_holdtime.setValue(1)
        self.doubleSpinBox_holdtime.setObjectName("doubleSpinBox_holdtime")
        self.label_s_hold = QtWidgets.QLabel(self.widget)
        self.label_s_hold.setGeometry(QtCore.QRect(80, 40, 22, 22))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_s_hold.setFont(font)
        self.label_s_hold.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_s_hold.setText("")
        self.label_s_hold.setPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/clock.png"))
        self.label_s_hold.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_s_hold.setObjectName("label_s_hold")
        self.groupBox_maincontrols = QtWidgets.QGroupBox(self.widget)
        self.groupBox_maincontrols.setGeometry(QtCore.QRect(310, 70, 171, 61))
        self.groupBox_maincontrols.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.groupBox_maincontrols.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_maincontrols.setFlat(True)
        self.groupBox_maincontrols.setObjectName("groupBox_maincontrols")
        self.pushButton_sequencer_prevstep = QtWidgets.QPushButton(self.groupBox_maincontrols)
        self.pushButton_sequencer_prevstep.setGeometry(QtCore.QRect(10, 20, 31, 31))
        self.pushButton_sequencer_prevstep.setStyleSheet("background-color: rgba(15, 15, 20, 200);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_sequencer_prevstep.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/arrow-step-back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sequencer_prevstep.setIcon(icon3)
        self.pushButton_sequencer_prevstep.setObjectName("pushButton_sequencer_prevstep")
        self.pushButton_sequencer_play = QtWidgets.QPushButton(self.groupBox_maincontrols)
        self.pushButton_sequencer_play.setGeometry(QtCore.QRect(50, 20, 31, 31))
        self.pushButton_sequencer_play.setStyleSheet("background-color: rgba(15, 15, 20, 200);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_sequencer_play.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/control.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sequencer_play.setIcon(icon4)
        self.pushButton_sequencer_play.setCheckable(True)
        self.pushButton_sequencer_play.setObjectName("pushButton_sequencer_play")
        self.pushButton_sequencer_nextstep = QtWidgets.QPushButton(self.groupBox_maincontrols)
        self.pushButton_sequencer_nextstep.setGeometry(QtCore.QRect(90, 20, 31, 31))
        self.pushButton_sequencer_nextstep.setStyleSheet("background-color: rgba(15, 15, 20, 200);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_sequencer_nextstep.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/arrow-step-over.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sequencer_nextstep.setIcon(icon5)
        self.pushButton_sequencer_nextstep.setObjectName("pushButton_sequencer_nextstep")
        self.pushButton_sequencer_repeat = QtWidgets.QPushButton(self.groupBox_maincontrols)
        self.pushButton_sequencer_repeat.setGeometry(QtCore.QRect(130, 20, 31, 31))
        self.pushButton_sequencer_repeat.setStyleSheet("background-color: rgba(15, 15, 20, 200);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_sequencer_repeat.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/arrow-repeat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sequencer_repeat.setIcon(icon6)
        self.pushButton_sequencer_repeat.setCheckable(True)
        self.pushButton_sequencer_repeat.setObjectName("pushButton_sequencer_repeat")
        self.line = QtWidgets.QFrame(self.frame_sequencer)
        self.line.setGeometry(QtCore.QRect(130, 110, 4, 32))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_duplicateStep = QtWidgets.QPushButton(self.frame_sequencer)
        self.pushButton_duplicateStep.setGeometry(QtCore.QRect(140, 110, 31, 31))
        self.pushButton_duplicateStep.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/document-copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_duplicateStep.setIcon(icon7)
        self.pushButton_duplicateStep.setObjectName("pushButton_duplicateStep")
        self.pushButton_moveStepLeft = QtWidgets.QPushButton(self.frame_sequencer)
        self.pushButton_moveStepLeft.setGeometry(QtCore.QRect(180, 110, 31, 31))
        self.pushButton_moveStepLeft.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/arrow-skip-180.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_moveStepLeft.setIcon(icon8)
        self.pushButton_moveStepLeft.setObjectName("pushButton_moveStepLeft")
        self.pushButton_moveStepRight = QtWidgets.QPushButton(self.frame_sequencer)
        self.pushButton_moveStepRight.setGeometry(QtCore.QRect(220, 110, 31, 31))
        self.pushButton_moveStepRight.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/arrow-skip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_moveStepRight.setIcon(icon9)
        self.pushButton_moveStepRight.setObjectName("pushButton_moveStepRight")
        self.pushButton_replaceStep = QtWidgets.QPushButton(self.frame_sequencer)
        self.pushButton_replaceStep.setGeometry(QtCore.QRect(50, 110, 31, 31))
        self.pushButton_replaceStep.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/arrow-step.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_replaceStep.setIcon(icon10)
        self.pushButton_replaceStep.setObjectName("pushButton_replaceStep")
        self.line_2 = QtWidgets.QFrame(self.frame_sequencer)
        self.line_2.setGeometry(QtCore.QRect(260, 110, 4, 32))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_importSequence = QtWidgets.QPushButton(self.frame_sequencer)
        self.pushButton_importSequence.setGeometry(QtCore.QRect(270, 110, 31, 31))
        self.pushButton_importSequence.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/document-import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_importSequence.setIcon(icon11)
        self.pushButton_importSequence.setObjectName("pushButton_importSequence")
        self.pushButton_exportSequence = QtWidgets.QPushButton(self.frame_sequencer)
        self.pushButton_exportSequence.setGeometry(QtCore.QRect(310, 110, 31, 31))
        self.pushButton_exportSequence.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/document-export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_exportSequence.setIcon(icon12)
        self.pushButton_exportSequence.setObjectName("pushButton_exportSequence")
        self.widget_information = QtWidgets.QWidget(self.frame_sequencer)
        self.widget_information.setGeometry(QtCore.QRect(10, 290, 491, 41))
        self.widget_information.setStyleSheet("background-color: rgba(15, 15, 20, 200);")
        self.widget_information.setObjectName("widget_information")
        self.lcdNumber_steps = QtWidgets.QLCDNumber(self.widget_information)
        self.lcdNumber_steps.setGeometry(QtCore.QRect(10, 10, 171, 23))
        self.lcdNumber_steps.setDigitCount(15)
        self.lcdNumber_steps.setProperty("value", 0.0)
        self.lcdNumber_steps.setObjectName("lcdNumber_steps")
        self.label_s_i_steps = QtWidgets.QLabel(self.widget_information)
        self.label_s_i_steps.setGeometry(QtCore.QRect(190, 10, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_s_i_steps.setFont(font)
        self.label_s_i_steps.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_s_i_steps.setObjectName("label_s_i_steps")
        self.lcdNumber_duration = QtWidgets.QLCDNumber(self.widget_information)
        self.lcdNumber_duration.setGeometry(QtCore.QRect(253, 10, 171, 23))
        self.lcdNumber_duration.setDigitCount(15)
        self.lcdNumber_duration.setObjectName("lcdNumber_duration")
        self.label_s_i_duration = QtWidgets.QLabel(self.widget_information)
        self.label_s_i_duration.setGeometry(QtCore.QRect(430, 10, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_s_i_duration.setFont(font)
        self.label_s_i_duration.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_s_i_duration.setObjectName("label_s_i_duration")
        self.groupBox_sequencer = QtWidgets.QGroupBox(self.frame_sequencer)
        self.groupBox_sequencer.setGeometry(QtCore.QRect(10, 10, 491, 91))
        self.groupBox_sequencer.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.groupBox_sequencer.setFlat(True)
        self.groupBox_sequencer.setObjectName("groupBox_sequencer")
        self.listWidget_sequence = QtWidgets.QListWidget(self.groupBox_sequencer)
        self.listWidget_sequence.setGeometry(QtCore.QRect(0, 20, 491, 71))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_sequence.setFont(font)
        self.listWidget_sequence.setStyleSheet("background-color: rgb(15, 15, 20);\n"
"alternate-background-color: rgb(30, 30, 40);\n"
"color: rgb(255, 255, 255);")
        self.listWidget_sequence.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget_sequence.setDragEnabled(True)
        self.listWidget_sequence.setAlternatingRowColors(True)
        self.listWidget_sequence.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_sequence.setUniformItemSizes(False)
        self.listWidget_sequence.setObjectName("listWidget_sequence")
        self.widget.raise_()
        self.pushButton_addStep.raise_()
        self.pushButton_deleteStep.raise_()
        self.line.raise_()
        self.pushButton_duplicateStep.raise_()
        self.pushButton_moveStepLeft.raise_()
        self.pushButton_moveStepRight.raise_()
        self.pushButton_replaceStep.raise_()
        self.line_2.raise_()
        self.pushButton_importSequence.raise_()
        self.pushButton_exportSequence.raise_()
        self.widget_information.raise_()
        self.groupBox_sequencer.raise_()
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setGeometry(QtCore.QRect(510, 410, 511, 181))
        self.frame_main.setStyleSheet("background-color: rgba(205, 205, 205, 120);")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setObjectName("frame_main")
        self.groupBox_quickcontrols = QtWidgets.QGroupBox(self.frame_main)
        self.groupBox_quickcontrols.setGeometry(QtCore.QRect(10, 10, 491, 161))
        self.groupBox_quickcontrols.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.groupBox_quickcontrols.setFlat(True)
        self.groupBox_quickcontrols.setObjectName("groupBox_quickcontrols")
        self.pushButton_qc_blackout = QtWidgets.QPushButton(self.groupBox_quickcontrols)
        self.pushButton_qc_blackout.setGeometry(QtCore.QRect(0, 20, 31, 31))
        self.pushButton_qc_blackout.setStyleSheet("background-color: rgba(255, 105, 105, 220);")
        self.pushButton_qc_blackout.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/light-bulb-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_qc_blackout.setIcon(icon13)
        self.pushButton_qc_blackout.setCheckable(True)
        self.pushButton_qc_blackout.setObjectName("pushButton_qc_blackout")
        self.label_qc_blackout = QtWidgets.QLabel(self.groupBox_quickcontrols)
        self.label_qc_blackout.setGeometry(QtCore.QRect(40, 20, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qc_blackout.setFont(font)
        self.label_qc_blackout.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_qc_blackout.setObjectName("label_qc_blackout")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1030, 600))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/background-1.png"))
        self.background.setObjectName("background")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 1011, 42))
        self.frame.setStyleSheet("background-color: rgba(205, 205, 205, 120);\n"
"border-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.comboBox_mididevice = QtWidgets.QComboBox(self.frame)
        self.comboBox_mididevice.setGeometry(QtCore.QRect(10, 10, 241, 22))
        self.comboBox_mididevice.setToolTip("")
        self.comboBox_mididevice.setStyleSheet("background-color: rgb(15, 15, 20);\n"
"alternate-background-color: rgb(30, 30, 40);\n"
"color: rgb(255, 255, 255);")
        self.comboBox_mididevice.setObjectName("comboBox_mididevice")
        self.label_info_mididevice = QtWidgets.QLabel(self.frame)
        self.label_info_mididevice.setGeometry(QtCore.QRect(260, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_info_mididevice.setFont(font)
        self.label_info_mididevice.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_info_mididevice.setObjectName("label_info_mididevice")
        self.pushButton_exportChannel = QtWidgets.QPushButton(self.frame)
        self.pushButton_exportChannel.setGeometry(QtCore.QRect(360, 5, 31, 31))
        self.pushButton_exportChannel.setText("")
        self.pushButton_exportChannel.setIcon(icon12)
        self.pushButton_exportChannel.setObjectName("pushButton_exportChannel")
        self.pushButton_importChannel = QtWidgets.QPushButton(self.frame)
        self.pushButton_importChannel.setGeometry(QtCore.QRect(320, 5, 31, 31))
        self.pushButton_importChannel.setText("")
        self.pushButton_importChannel.setIcon(icon11)
        self.pushButton_importChannel.setObjectName("pushButton_importChannel")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(310, 5, 4, 32))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.background.raise_()
        self.frame_channels.raise_()
        self.frame_channelproperties.raise_()
        self.frame_3.raise_()
        self.frame_sequencer.raise_()
        self.frame_main.raise_()
        self.frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1032, 21))
        self.menubar.setObjectName("menubar")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setCheckable(True)
        self.action.setObjectName("action")
        self.actionHide_Background = QtWidgets.QAction(MainWindow)
        self.actionHide_Background.setCheckable(True)
        self.actionHide_Background.setObjectName("actionHide_Background")
        self.menuView.addAction(self.actionHide_Background)
        self.menubar.addAction(self.menuView.menuAction())
        self.verticalSlider_a_1.valueChanged["int"].connect(self.label_a_value_1.setNum)
        self.verticalSlider_a_2.valueChanged["int"].connect(self.label_a_value_2.setNum)
        self.verticalSlider_a_3.valueChanged["int"].connect(self.label_a_value_3.setNum)
        self.verticalSlider_a_4.valueChanged["int"].connect(self.label_a_value_4.setNum)
        self.verticalSlider_a_5.valueChanged["int"].connect(self.label_a_value_5.setNum)
        self.verticalSlider_a_6.valueChanged["int"].connect(self.label_a_value_6.setNum)
        self.verticalSlider_a_7.valueChanged["int"].connect(self.label_a_value_7.setNum)
        self.verticalSlider_a_8.valueChanged["int"].connect(self.label_a_value_8.setNum)
        self.verticalSlider_a_9.valueChanged["int"].connect(self.label_a_value_9.setNum)
        self.verticalSlider_a_10.valueChanged["int"].connect(self.label_a_value_10.setNum)
        self.verticalSlider_a_11.valueChanged["int"].connect(self.label_a_value_11.setNum)
        self.verticalSlider_a_12.valueChanged["int"].connect(self.label_a_value_12.setNum)

        self.retranslateUi(MainWindow)
        self.listWidget_sequence.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_a_1.setText(_translate("MainWindow", "1"))
        self.label_a_2.setText(_translate("MainWindow", "2"))
        self.label_a_3.setText(_translate("MainWindow", "3"))
        self.label_a_4.setText(_translate("MainWindow", "4"))
        self.label_a_5.setText(_translate("MainWindow", "5"))
        self.label_a_6.setText(_translate("MainWindow", "6"))
        self.label_a_7.setText(_translate("MainWindow", "7"))
        self.label_a_8.setText(_translate("MainWindow", "8"))
        self.label_a_9.setText(_translate("MainWindow", "9"))
        self.label_a_10.setText(_translate("MainWindow", "10"))
        self.label_a_11.setText(_translate("MainWindow", "11"))
        self.label_a_12.setText(_translate("MainWindow", "12"))
        self.label_a_value_1.setText(_translate("MainWindow", "0"))
        self.label_a_value_2.setText(_translate("MainWindow", "0"))
        self.label_a_value_3.setText(_translate("MainWindow", "0"))
        self.label_a_value_4.setText(_translate("MainWindow", "0"))
        self.label_a_value_5.setText(_translate("MainWindow", "0"))
        self.label_a_value_6.setText(_translate("MainWindow", "0"))
        self.label_a_value_7.setText(_translate("MainWindow", "0"))
        self.label_a_value_8.setText(_translate("MainWindow", "0"))
        self.label_a_value_9.setText(_translate("MainWindow", "0"))
        self.label_a_value_10.setText(_translate("MainWindow", "0"))
        self.label_a_value_11.setText(_translate("MainWindow", "0"))
        self.label_a_value_12.setText(_translate("MainWindow", "0"))
        self.label_noneselected.setText(_translate("MainWindow", "Select a channel first to edit"))
        self.pushButton_lightcolor.setToolTip(_translate("MainWindow", "Click to change colour"))
        self.label_ce_channelname.setText(_translate("MainWindow", "Channel Name"))
        self.lineEdit_channelname.setPlaceholderText(_translate("MainWindow", "Default"))
        self.label_ce_channelcol.setText(_translate("MainWindow", "Channel Colour"))
        self.label_ce_currentval.setText(_translate("MainWindow", "Current Value"))
        self.plainTextEdit_notes.setPlaceholderText(_translate("MainWindow", "Enter notes here."))
        self.label_noneselected_2.setText(_translate("MainWindow", "Multi-Channel Edit Mode"))
        self.label_me_100.setText(_translate("MainWindow", "Set 100%"))
        self.label_me_0.setText(_translate("MainWindow", "Set 0%"))
        self.pushButton_addStep.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Add Step</span></p><p>Adds the current channel settings to a new step at the end.</p><p>Shortcut: A</p></body></html>"))
        self.pushButton_addStep.setShortcut(_translate("MainWindow", "A"))
        self.pushButton_deleteStep.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Delete Step</span></p><p>This will delete the selected step, or if none is selected then it deletes the last step.</p><p>Shortcut: X</p></body></html>"))
        self.pushButton_deleteStep.setShortcut(_translate("MainWindow", "X"))
        self.doubleSpinBox_fadetime.setSuffix(_translate("MainWindow", " s"))
        self.label_s_xfade.setToolTip(_translate("MainWindow", "Transition Time"))
        self.doubleSpinBox_holdtime.setSuffix(_translate("MainWindow", " s"))
        self.label_s_hold.setToolTip(_translate("MainWindow", "Hold Time"))
        self.groupBox_maincontrols.setTitle(_translate("MainWindow", "  Main Controls  "))
        self.pushButton_sequencer_prevstep.setToolTip(_translate("MainWindow", "Next Step"))
        self.pushButton_sequencer_prevstep.setShortcut(_translate("MainWindow", "Left"))
        self.pushButton_sequencer_play.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Play Sequence</span></p></body></html>"))
        self.pushButton_sequencer_nextstep.setToolTip(_translate("MainWindow", "Next Step"))
        self.pushButton_sequencer_nextstep.setShortcut(_translate("MainWindow", "Right"))
        self.pushButton_sequencer_repeat.setToolTip(_translate("MainWindow", "Loop Sequence"))
        self.pushButton_duplicateStep.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Duplicate Step</span></p><p>Shortcut: D</p></body></html>"))
        self.pushButton_duplicateStep.setShortcut(_translate("MainWindow", "D"))
        self.pushButton_moveStepLeft.setToolTip(_translate("MainWindow", "Move Selected Step Left"))
        self.pushButton_moveStepRight.setToolTip(_translate("MainWindow", "Move Selected Step Right"))
        self.pushButton_replaceStep.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Replace Step</span></p><p>Replaces the settings on the step with the current settings.</p><p>Shortcut: Shift+A</p></body></html>"))
        self.pushButton_replaceStep.setShortcut(_translate("MainWindow", "Shift+A"))
        self.pushButton_importSequence.setToolTip(_translate("MainWindow", "Import Sequence"))
        self.pushButton_exportSequence.setToolTip(_translate("MainWindow", "Export Sequence"))
        self.label_s_i_steps.setText(_translate("MainWindow", "Steps"))
        self.label_s_i_duration.setText(_translate("MainWindow", "Duration"))
        self.groupBox_sequencer.setTitle(_translate("MainWindow", "Sequencer  "))
        self.groupBox_quickcontrols.setTitle(_translate("MainWindow", "Quick Controls"))
        self.pushButton_qc_blackout.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">Blackout</span></p></body></html>"))
        self.label_qc_blackout.setText(_translate("MainWindow", "Blackout"))
        self.label_info_mididevice.setText(_translate("MainWindow", "MIDI Desk"))
        self.pushButton_exportChannel.setToolTip(_translate("MainWindow", "Export Channel Settings"))
        self.pushButton_importChannel.setToolTip(_translate("MainWindow", "Import Channel Settings"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.action.setText(_translate("MainWindow", "Simple Mode"))
        self.actionHide_Background.setText(_translate("MainWindow", "Hide Background"))

