# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\mitgobla\Documents\GitHub\GroupQuiz\UI\lighting-control.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import os
SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 640)
        MainWindow.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 491, 241))
        self.groupBox.setObjectName("groupBox")
        self.verticalSlider_a_1 = QtWidgets.QSlider(self.groupBox)
        self.verticalSlider_a_1.setGeometry(QtCore.QRect(10, 40, 32, 169))
        self.verticalSlider_a_1.setMaximum(127)
        self.verticalSlider_a_1.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_1.setInvertedAppearance(False)
        self.verticalSlider_a_1.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_1.setTickInterval(8)
        self.verticalSlider_a_1.setObjectName("verticalSlider_a_1")
        self.verticalSlider_a_2 = QtWidgets.QSlider(self.groupBox)
        self.verticalSlider_a_2.setGeometry(QtCore.QRect(50, 40, 32, 169))
        self.verticalSlider_a_2.setMaximum(127)
        self.verticalSlider_a_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_2.setInvertedAppearance(False)
        self.verticalSlider_a_2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_2.setTickInterval(8)
        self.verticalSlider_a_2.setObjectName("verticalSlider_a_2")
        self.verticalSlider_a_3 = QtWidgets.QSlider(self.groupBox)
        self.verticalSlider_a_3.setGeometry(QtCore.QRect(90, 40, 32, 169))
        self.verticalSlider_a_3.setMaximum(127)
        self.verticalSlider_a_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_3.setInvertedAppearance(False)
        self.verticalSlider_a_3.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_3.setTickInterval(8)
        self.verticalSlider_a_3.setObjectName("verticalSlider_a_3")
        self.verticalSlider_a_4 = QtWidgets.QSlider(self.groupBox)
        self.verticalSlider_a_4.setGeometry(QtCore.QRect(130, 40, 32, 169))
        self.verticalSlider_a_4.setMaximum(127)
        self.verticalSlider_a_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_4.setInvertedAppearance(False)
        self.verticalSlider_a_4.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_4.setTickInterval(8)
        self.verticalSlider_a_4.setObjectName("verticalSlider_a_4")
        self.verticalSlider_a_5 = QtWidgets.QSlider(self.groupBox)
        self.verticalSlider_a_5.setGeometry(QtCore.QRect(170, 40, 32, 169))
        self.verticalSlider_a_5.setMaximum(127)
        self.verticalSlider_a_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_5.setInvertedAppearance(False)
        self.verticalSlider_a_5.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_5.setTickInterval(8)
        self.verticalSlider_a_5.setObjectName("verticalSlider_a_5")
        self.verticalSlider_a_6 = QtWidgets.QSlider(self.groupBox)
        self.verticalSlider_a_6.setGeometry(QtCore.QRect(210, 40, 32, 169))
        self.verticalSlider_a_6.setMaximum(127)
        self.verticalSlider_a_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_6.setInvertedAppearance(False)
        self.verticalSlider_a_6.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_6.setTickInterval(8)
        self.verticalSlider_a_6.setObjectName("verticalSlider_a_6")
        self.verticalSlider_a_7 = QtWidgets.QSlider(self.groupBox)
        self.verticalSlider_a_7.setGeometry(QtCore.QRect(250, 40, 32, 169))
        self.verticalSlider_a_7.setMaximum(127)
        self.verticalSlider_a_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_7.setInvertedAppearance(False)
        self.verticalSlider_a_7.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_7.setTickInterval(8)
        self.verticalSlider_a_7.setObjectName("verticalSlider_a_7")
        self.verticalSlider_a_8 = QtWidgets.QSlider(self.groupBox)
        self.verticalSlider_a_8.setGeometry(QtCore.QRect(290, 40, 32, 169))
        self.verticalSlider_a_8.setMaximum(127)
        self.verticalSlider_a_8.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_8.setInvertedAppearance(False)
        self.verticalSlider_a_8.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_8.setTickInterval(8)
        self.verticalSlider_a_8.setObjectName("verticalSlider_a_8")
        self.verticalSlider_a_9 = QtWidgets.QSlider(self.groupBox)
        self.verticalSlider_a_9.setGeometry(QtCore.QRect(330, 40, 32, 169))
        self.verticalSlider_a_9.setMaximum(127)
        self.verticalSlider_a_9.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_9.setInvertedAppearance(False)
        self.verticalSlider_a_9.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_9.setTickInterval(8)
        self.verticalSlider_a_9.setObjectName("verticalSlider_a_9")
        self.verticalSlider_a_10 = QtWidgets.QSlider(self.groupBox)
        self.verticalSlider_a_10.setGeometry(QtCore.QRect(370, 40, 32, 169))
        self.verticalSlider_a_10.setMaximum(127)
        self.verticalSlider_a_10.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_10.setInvertedAppearance(False)
        self.verticalSlider_a_10.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_10.setTickInterval(8)
        self.verticalSlider_a_10.setObjectName("verticalSlider_a_10")
        self.verticalSlider_a_11 = QtWidgets.QSlider(self.groupBox)
        self.verticalSlider_a_11.setGeometry(QtCore.QRect(410, 40, 32, 169))
        self.verticalSlider_a_11.setMaximum(127)
        self.verticalSlider_a_11.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_11.setInvertedAppearance(False)
        self.verticalSlider_a_11.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_11.setTickInterval(8)
        self.verticalSlider_a_11.setObjectName("verticalSlider_a_11")
        self.verticalSlider_a_12 = QtWidgets.QSlider(self.groupBox)
        self.verticalSlider_a_12.setGeometry(QtCore.QRect(450, 40, 32, 169))
        self.verticalSlider_a_12.setMaximum(127)
        self.verticalSlider_a_12.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_a_12.setInvertedAppearance(False)
        self.verticalSlider_a_12.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_a_12.setTickInterval(8)
        self.verticalSlider_a_12.setObjectName("verticalSlider_a_12")
        self.label_a_1 = QtWidgets.QLabel(self.groupBox)
        self.label_a_1.setGeometry(QtCore.QRect(10, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_1.setFont(font)
        self.label_a_1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_1.setObjectName("label_a_1")
        self.label_a_2 = QtWidgets.QLabel(self.groupBox)
        self.label_a_2.setGeometry(QtCore.QRect(50, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_2.setFont(font)
        self.label_a_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_2.setObjectName("label_a_2")
        self.label_a_3 = QtWidgets.QLabel(self.groupBox)
        self.label_a_3.setGeometry(QtCore.QRect(90, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_3.setFont(font)
        self.label_a_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_3.setObjectName("label_a_3")
        self.label_a_4 = QtWidgets.QLabel(self.groupBox)
        self.label_a_4.setGeometry(QtCore.QRect(130, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_4.setFont(font)
        self.label_a_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_4.setObjectName("label_a_4")
        self.label_a_5 = QtWidgets.QLabel(self.groupBox)
        self.label_a_5.setGeometry(QtCore.QRect(170, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_5.setFont(font)
        self.label_a_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_5.setObjectName("label_a_5")
        self.label_a_6 = QtWidgets.QLabel(self.groupBox)
        self.label_a_6.setGeometry(QtCore.QRect(210, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_6.setFont(font)
        self.label_a_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_6.setObjectName("label_a_6")
        self.label_a_7 = QtWidgets.QLabel(self.groupBox)
        self.label_a_7.setGeometry(QtCore.QRect(250, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_7.setFont(font)
        self.label_a_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_7.setObjectName("label_a_7")
        self.label_a_8 = QtWidgets.QLabel(self.groupBox)
        self.label_a_8.setGeometry(QtCore.QRect(290, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_8.setFont(font)
        self.label_a_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_8.setObjectName("label_a_8")
        self.label_a_9 = QtWidgets.QLabel(self.groupBox)
        self.label_a_9.setGeometry(QtCore.QRect(330, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_9.setFont(font)
        self.label_a_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_9.setObjectName("label_a_9")
        self.label_a_10 = QtWidgets.QLabel(self.groupBox)
        self.label_a_10.setGeometry(QtCore.QRect(370, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_10.setFont(font)
        self.label_a_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_10.setObjectName("label_a_10")
        self.label_a_11 = QtWidgets.QLabel(self.groupBox)
        self.label_a_11.setGeometry(QtCore.QRect(410, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_11.setFont(font)
        self.label_a_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_11.setObjectName("label_a_11")
        self.label_a_12 = QtWidgets.QLabel(self.groupBox)
        self.label_a_12.setGeometry(QtCore.QRect(450, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_12.setFont(font)
        self.label_a_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_a_12.setObjectName("label_a_12")
        self.label_a_value_1 = QtWidgets.QLabel(self.groupBox)
        self.label_a_value_1.setGeometry(QtCore.QRect(10, 210, 32, 21))
        self.label_a_value_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_1.setObjectName("label_a_value_1")
        self.label_a_value_2 = QtWidgets.QLabel(self.groupBox)
        self.label_a_value_2.setGeometry(QtCore.QRect(50, 210, 32, 21))
        self.label_a_value_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_2.setObjectName("label_a_value_2")
        self.label_a_value_3 = QtWidgets.QLabel(self.groupBox)
        self.label_a_value_3.setGeometry(QtCore.QRect(90, 210, 32, 21))
        self.label_a_value_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_3.setObjectName("label_a_value_3")
        self.label_a_value_4 = QtWidgets.QLabel(self.groupBox)
        self.label_a_value_4.setGeometry(QtCore.QRect(130, 210, 32, 21))
        self.label_a_value_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_4.setObjectName("label_a_value_4")
        self.label_a_value_5 = QtWidgets.QLabel(self.groupBox)
        self.label_a_value_5.setGeometry(QtCore.QRect(170, 210, 32, 21))
        self.label_a_value_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_5.setObjectName("label_a_value_5")
        self.label_a_value_6 = QtWidgets.QLabel(self.groupBox)
        self.label_a_value_6.setGeometry(QtCore.QRect(210, 210, 32, 21))
        self.label_a_value_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_6.setObjectName("label_a_value_6")
        self.label_a_value_7 = QtWidgets.QLabel(self.groupBox)
        self.label_a_value_7.setGeometry(QtCore.QRect(250, 210, 32, 21))
        self.label_a_value_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_7.setObjectName("label_a_value_7")
        self.label_a_value_8 = QtWidgets.QLabel(self.groupBox)
        self.label_a_value_8.setGeometry(QtCore.QRect(290, 210, 32, 21))
        self.label_a_value_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_8.setObjectName("label_a_value_8")
        self.label_a_value_9 = QtWidgets.QLabel(self.groupBox)
        self.label_a_value_9.setGeometry(QtCore.QRect(330, 210, 32, 21))
        self.label_a_value_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_9.setObjectName("label_a_value_9")
        self.label_a_value_10 = QtWidgets.QLabel(self.groupBox)
        self.label_a_value_10.setGeometry(QtCore.QRect(370, 210, 32, 21))
        self.label_a_value_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_10.setObjectName("label_a_value_10")
        self.label_a_value_11 = QtWidgets.QLabel(self.groupBox)
        self.label_a_value_11.setGeometry(QtCore.QRect(410, 210, 32, 21))
        self.label_a_value_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_11.setObjectName("label_a_value_11")
        self.label_a_value_12 = QtWidgets.QLabel(self.groupBox)
        self.label_a_value_12.setGeometry(QtCore.QRect(450, 210, 32, 21))
        self.label_a_value_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_value_12.setObjectName("label_a_value_12")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 260, 491, 241))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalSlider_b_1 = QtWidgets.QSlider(self.groupBox_2)
        self.verticalSlider_b_1.setGeometry(QtCore.QRect(10, 40, 32, 169))
        self.verticalSlider_b_1.setMaximum(127)
        self.verticalSlider_b_1.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_b_1.setInvertedAppearance(False)
        self.verticalSlider_b_1.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_b_1.setTickInterval(8)
        self.verticalSlider_b_1.setObjectName("verticalSlider_b_1")
        self.label_b_1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_1.setGeometry(QtCore.QRect(10, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_b_1.setFont(font)
        self.label_b_1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_b_1.setObjectName("label_b_1")
        self.label_b_value_1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_value_1.setGeometry(QtCore.QRect(10, 210, 32, 21))
        self.label_b_value_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b_value_1.setObjectName("label_b_value_1")
        self.label_b_value_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_value_2.setGeometry(QtCore.QRect(50, 210, 32, 21))
        self.label_b_value_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b_value_2.setObjectName("label_b_value_2")
        self.verticalSlider_b_2 = QtWidgets.QSlider(self.groupBox_2)
        self.verticalSlider_b_2.setGeometry(QtCore.QRect(50, 40, 32, 169))
        self.verticalSlider_b_2.setMaximum(127)
        self.verticalSlider_b_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_b_2.setInvertedAppearance(False)
        self.verticalSlider_b_2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_b_2.setTickInterval(8)
        self.verticalSlider_b_2.setObjectName("verticalSlider_b_2")
        self.label_b_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_2.setGeometry(QtCore.QRect(50, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_b_2.setFont(font)
        self.label_b_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_b_2.setObjectName("label_b_2")
        self.label_b_value_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_value_3.setGeometry(QtCore.QRect(90, 210, 32, 21))
        self.label_b_value_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b_value_3.setObjectName("label_b_value_3")
        self.verticalSlider_b_3 = QtWidgets.QSlider(self.groupBox_2)
        self.verticalSlider_b_3.setGeometry(QtCore.QRect(90, 40, 32, 169))
        self.verticalSlider_b_3.setMaximum(127)
        self.verticalSlider_b_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_b_3.setInvertedAppearance(False)
        self.verticalSlider_b_3.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_b_3.setTickInterval(8)
        self.verticalSlider_b_3.setObjectName("verticalSlider_b_3")
        self.label_b_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_3.setGeometry(QtCore.QRect(90, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_b_3.setFont(font)
        self.label_b_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_b_3.setObjectName("label_b_3")
        self.label_b_value_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_value_4.setGeometry(QtCore.QRect(130, 210, 32, 21))
        self.label_b_value_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b_value_4.setObjectName("label_b_value_4")
        self.verticalSlider_b_4 = QtWidgets.QSlider(self.groupBox_2)
        self.verticalSlider_b_4.setGeometry(QtCore.QRect(130, 40, 32, 169))
        self.verticalSlider_b_4.setMaximum(127)
        self.verticalSlider_b_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_b_4.setInvertedAppearance(False)
        self.verticalSlider_b_4.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_b_4.setTickInterval(8)
        self.verticalSlider_b_4.setObjectName("verticalSlider_b_4")
        self.label_b_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_4.setGeometry(QtCore.QRect(130, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_b_4.setFont(font)
        self.label_b_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_b_4.setObjectName("label_b_4")
        self.label_b_value_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_value_5.setGeometry(QtCore.QRect(170, 210, 32, 21))
        self.label_b_value_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b_value_5.setObjectName("label_b_value_5")
        self.verticalSlider_b_5 = QtWidgets.QSlider(self.groupBox_2)
        self.verticalSlider_b_5.setGeometry(QtCore.QRect(170, 40, 32, 169))
        self.verticalSlider_b_5.setMaximum(127)
        self.verticalSlider_b_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_b_5.setInvertedAppearance(False)
        self.verticalSlider_b_5.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_b_5.setTickInterval(8)
        self.verticalSlider_b_5.setObjectName("verticalSlider_b_5")
        self.label_b_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_5.setGeometry(QtCore.QRect(170, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_b_5.setFont(font)
        self.label_b_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_b_5.setObjectName("label_b_5")
        self.label_b_value_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_value_6.setGeometry(QtCore.QRect(210, 210, 32, 21))
        self.label_b_value_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b_value_6.setObjectName("label_b_value_6")
        self.verticalSlider_b_6 = QtWidgets.QSlider(self.groupBox_2)
        self.verticalSlider_b_6.setGeometry(QtCore.QRect(210, 40, 32, 169))
        self.verticalSlider_b_6.setMaximum(127)
        self.verticalSlider_b_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_b_6.setInvertedAppearance(False)
        self.verticalSlider_b_6.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_b_6.setTickInterval(8)
        self.verticalSlider_b_6.setObjectName("verticalSlider_b_6")
        self.label_b_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_6.setGeometry(QtCore.QRect(210, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_b_6.setFont(font)
        self.label_b_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_b_6.setObjectName("label_b_6")
        self.label_b_value_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_value_7.setGeometry(QtCore.QRect(250, 210, 32, 21))
        self.label_b_value_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b_value_7.setObjectName("label_b_value_7")
        self.verticalSlider_b_7 = QtWidgets.QSlider(self.groupBox_2)
        self.verticalSlider_b_7.setGeometry(QtCore.QRect(250, 40, 32, 169))
        self.verticalSlider_b_7.setMaximum(127)
        self.verticalSlider_b_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_b_7.setInvertedAppearance(False)
        self.verticalSlider_b_7.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_b_7.setTickInterval(8)
        self.verticalSlider_b_7.setObjectName("verticalSlider_b_7")
        self.label_b_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_7.setGeometry(QtCore.QRect(250, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_b_7.setFont(font)
        self.label_b_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_b_7.setObjectName("label_b_7")
        self.label_b_value_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_value_8.setGeometry(QtCore.QRect(290, 210, 32, 21))
        self.label_b_value_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b_value_8.setObjectName("label_b_value_8")
        self.verticalSlider_b_8 = QtWidgets.QSlider(self.groupBox_2)
        self.verticalSlider_b_8.setGeometry(QtCore.QRect(290, 40, 32, 169))
        self.verticalSlider_b_8.setMaximum(127)
        self.verticalSlider_b_8.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_b_8.setInvertedAppearance(False)
        self.verticalSlider_b_8.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_b_8.setTickInterval(8)
        self.verticalSlider_b_8.setObjectName("verticalSlider_b_8")
        self.label_b_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_8.setGeometry(QtCore.QRect(290, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_b_8.setFont(font)
        self.label_b_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_b_8.setObjectName("label_b_8")
        self.label_b_value_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_value_9.setGeometry(QtCore.QRect(330, 210, 32, 21))
        self.label_b_value_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b_value_9.setObjectName("label_b_value_9")
        self.verticalSlider_b_9 = QtWidgets.QSlider(self.groupBox_2)
        self.verticalSlider_b_9.setGeometry(QtCore.QRect(330, 40, 32, 169))
        self.verticalSlider_b_9.setMaximum(127)
        self.verticalSlider_b_9.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_b_9.setInvertedAppearance(False)
        self.verticalSlider_b_9.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_b_9.setTickInterval(8)
        self.verticalSlider_b_9.setObjectName("verticalSlider_b_9")
        self.label_b_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_9.setGeometry(QtCore.QRect(330, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_b_9.setFont(font)
        self.label_b_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_b_9.setObjectName("label_b_9")
        self.label_b_value_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_value_10.setGeometry(QtCore.QRect(370, 210, 32, 21))
        self.label_b_value_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b_value_10.setObjectName("label_b_value_10")
        self.verticalSlider_b_10 = QtWidgets.QSlider(self.groupBox_2)
        self.verticalSlider_b_10.setGeometry(QtCore.QRect(370, 40, 32, 169))
        self.verticalSlider_b_10.setMaximum(127)
        self.verticalSlider_b_10.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_b_10.setInvertedAppearance(False)
        self.verticalSlider_b_10.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_b_10.setTickInterval(8)
        self.verticalSlider_b_10.setObjectName("verticalSlider_b_10")
        self.label_b_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_10.setGeometry(QtCore.QRect(370, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_b_10.setFont(font)
        self.label_b_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_b_10.setObjectName("label_b_10")
        self.label_b_value_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_value_11.setGeometry(QtCore.QRect(410, 210, 32, 21))
        self.label_b_value_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b_value_11.setObjectName("label_b_value_11")
        self.verticalSlider_b_11 = QtWidgets.QSlider(self.groupBox_2)
        self.verticalSlider_b_11.setGeometry(QtCore.QRect(410, 40, 32, 169))
        self.verticalSlider_b_11.setMaximum(127)
        self.verticalSlider_b_11.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_b_11.setInvertedAppearance(False)
        self.verticalSlider_b_11.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_b_11.setTickInterval(8)
        self.verticalSlider_b_11.setObjectName("verticalSlider_b_11")
        self.label_b_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_11.setGeometry(QtCore.QRect(410, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_b_11.setFont(font)
        self.label_b_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_b_11.setObjectName("label_b_11")
        self.label_b_value_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_value_12.setGeometry(QtCore.QRect(450, 210, 32, 21))
        self.label_b_value_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b_value_12.setObjectName("label_b_value_12")
        self.verticalSlider_b_12 = QtWidgets.QSlider(self.groupBox_2)
        self.verticalSlider_b_12.setGeometry(QtCore.QRect(450, 40, 32, 169))
        self.verticalSlider_b_12.setMaximum(127)
        self.verticalSlider_b_12.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_b_12.setInvertedAppearance(False)
        self.verticalSlider_b_12.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_b_12.setTickInterval(8)
        self.verticalSlider_b_12.setObjectName("verticalSlider_b_12")
        self.label_b_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_b_12.setGeometry(QtCore.QRect(450, 10, 32, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_b_12.setFont(font)
        self.label_b_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_b_12.setObjectName("label_b_12")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 510, 491, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_flash_1 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_flash_1.setGeometry(QtCore.QRect(10, 20, 32, 51))
        self.pushButton_flash_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/lightning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_flash_1.setIcon(icon)
        self.pushButton_flash_1.setObjectName("pushButton_flash_1")
        self.pushButton_flash_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_flash_2.setGeometry(QtCore.QRect(50, 20, 32, 51))
        self.pushButton_flash_2.setText("")
        self.pushButton_flash_2.setIcon(icon)
        self.pushButton_flash_2.setObjectName("pushButton_flash_2")
        self.pushButton_flash_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_flash_3.setGeometry(QtCore.QRect(90, 20, 32, 51))
        self.pushButton_flash_3.setText("")
        self.pushButton_flash_3.setIcon(icon)
        self.pushButton_flash_3.setObjectName("pushButton_flash_3")
        self.pushButton_flash_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_flash_4.setGeometry(QtCore.QRect(130, 20, 32, 51))
        self.pushButton_flash_4.setText("")
        self.pushButton_flash_4.setIcon(icon)
        self.pushButton_flash_4.setObjectName("pushButton_flash_4")
        self.pushButton_flash_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_flash_5.setGeometry(QtCore.QRect(170, 20, 32, 51))
        self.pushButton_flash_5.setText("")
        self.pushButton_flash_5.setIcon(icon)
        self.pushButton_flash_5.setObjectName("pushButton_flash_5")
        self.pushButton_flash_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_flash_6.setGeometry(QtCore.QRect(210, 20, 32, 51))
        self.pushButton_flash_6.setText("")
        self.pushButton_flash_6.setIcon(icon)
        self.pushButton_flash_6.setObjectName("pushButton_flash_6")
        self.pushButton_flash_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_flash_7.setGeometry(QtCore.QRect(250, 20, 32, 51))
        self.pushButton_flash_7.setText("")
        self.pushButton_flash_7.setIcon(icon)
        self.pushButton_flash_7.setObjectName("pushButton_flash_7")
        self.pushButton_flash_8 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_flash_8.setGeometry(QtCore.QRect(290, 20, 32, 51))
        self.pushButton_flash_8.setText("")
        self.pushButton_flash_8.setIcon(icon)
        self.pushButton_flash_8.setObjectName("pushButton_flash_8")
        self.pushButton_flash_9 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_flash_9.setGeometry(QtCore.QRect(330, 20, 32, 51))
        self.pushButton_flash_9.setText("")
        self.pushButton_flash_9.setIcon(icon)
        self.pushButton_flash_9.setObjectName("pushButton_flash_9")
        self.pushButton_flash_10 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_flash_10.setGeometry(QtCore.QRect(370, 20, 32, 51))
        self.pushButton_flash_10.setText("")
        self.pushButton_flash_10.setIcon(icon)
        self.pushButton_flash_10.setObjectName("pushButton_flash_10")
        self.pushButton_flash_11 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_flash_11.setGeometry(QtCore.QRect(410, 20, 32, 51))
        self.pushButton_flash_11.setText("")
        self.pushButton_flash_11.setIcon(icon)
        self.pushButton_flash_11.setObjectName("pushButton_flash_11")
        self.pushButton_flash_12 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_flash_12.setGeometry(QtCore.QRect(450, 20, 32, 51))
        self.pushButton_flash_12.setText("")
        self.pushButton_flash_12.setIcon(icon)
        self.pushButton_flash_12.setObjectName("pushButton_flash_12")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(510, 10, 511, 301))
        self.groupBox_4.setObjectName("groupBox_4")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 451, 71))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        self.listWidget.setFont(font)
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.pushButton_addStep = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_addStep.setGeometry(QtCore.QRect(470, 20, 31, 31))
        self.pushButton_addStep.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/plus-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_addStep.setIcon(icon1)
        self.pushButton_addStep.setObjectName("pushButton_addStep")
        self.pushButton_deleteStep = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_deleteStep.setGeometry(QtCore.QRect(470, 60, 31, 31))
        self.pushButton_deleteStep.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/cross-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_deleteStep.setIcon(icon2)
        self.pushButton_deleteStep.setObjectName("pushButton_deleteStep")
        self.label_s_xfade = QtWidgets.QLabel(self.groupBox_4)
        self.label_s_xfade.setGeometry(QtCore.QRect(80, 100, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_s_xfade.setFont(font)
        self.label_s_xfade.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_s_xfade.setObjectName("label_s_xfade")
        self.doubleSpinBox_fadetime = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_fadetime.setGeometry(QtCore.QRect(10, 100, 62, 22))
        self.doubleSpinBox_fadetime.setDecimals(1)
        self.doubleSpinBox_fadetime.setMinimum(0.1)
        self.doubleSpinBox_fadetime.setObjectName("doubleSpinBox_fadetime")
        self.doubleSpinBox_holdtime = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_holdtime.setGeometry(QtCore.QRect(10, 130, 62, 22))
        self.doubleSpinBox_holdtime.setDecimals(1)
        self.doubleSpinBox_holdtime.setMinimum(0.1)
        self.doubleSpinBox_holdtime.setObjectName("doubleSpinBox_holdtime")
        self.label_s_hold = QtWidgets.QLabel(self.groupBox_4)
        self.label_s_hold.setGeometry(QtCore.QRect(80, 130, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_s_hold.setFont(font)
        self.label_s_hold.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_s_hold.setObjectName("label_s_hold")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(510, 320, 511, 271))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_main_sequencerplay = QtWidgets.QLabel(self.groupBox_5)
        self.label_main_sequencerplay.setGeometry(QtCore.QRect(370, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_main_sequencerplay.setFont(font)
        self.label_main_sequencerplay.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_main_sequencerplay.setObjectName("label_main_sequencerplay")
        self.pushButton_main_sequencerplay = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_main_sequencerplay.setGeometry(QtCore.QRect(330, 20, 31, 31))
        self.pushButton_main_sequencerplay.setText("")
        self.pushButton_main_sequencerplay.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/control.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_main_sequencerplay.setIcon(icon3)
        self.pushButton_main_sequencerplay.setObjectName("pushButton_main_sequencerplay")
        self.label_main_sequencerstep = QtWidgets.QLabel(self.groupBox_5)
        self.label_main_sequencerstep.setGeometry(QtCore.QRect(370, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_main_sequencerstep.setFont(font)
        self.label_main_sequencerstep.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_main_sequencerstep.setObjectName("label_main_sequencerstep")
        self.pushButton_main_sequencerstep = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_main_sequencerstep.setGeometry(QtCore.QRect(330, 60, 31, 31))
        self.pushButton_main_sequencerstep.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(SCRIPT_DIR+"/resources/arrow-step-over.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_main_sequencerstep.setIcon(icon4)
        self.pushButton_main_sequencerstep.setObjectName("pushButton_main_sequencerstep")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.listWidget.setCurrentRow(0)
        self.verticalSlider_a_1.valueChanged['int'].connect(self.label_a_value_1.setNum)
        self.verticalSlider_a_2.valueChanged['int'].connect(self.label_a_value_2.setNum)
        self.verticalSlider_a_3.valueChanged['int'].connect(self.label_a_value_3.setNum)
        self.verticalSlider_a_4.valueChanged['int'].connect(self.label_a_value_4.setNum)
        self.verticalSlider_a_5.valueChanged['int'].connect(self.label_a_value_5.setNum)
        self.verticalSlider_a_6.valueChanged['int'].connect(self.label_a_value_6.setNum)
        self.verticalSlider_a_7.valueChanged['int'].connect(self.label_a_value_7.setNum)
        self.verticalSlider_a_8.valueChanged['int'].connect(self.label_a_value_8.setNum)
        self.verticalSlider_a_9.valueChanged['int'].connect(self.label_a_value_9.setNum)
        self.verticalSlider_a_10.valueChanged['int'].connect(self.label_a_value_10.setNum)
        self.verticalSlider_a_11.valueChanged['int'].connect(self.label_a_value_11.setNum)
        self.verticalSlider_a_12.valueChanged['int'].connect(self.label_a_value_12.setNum)
        self.verticalSlider_b_1.valueChanged['int'].connect(self.label_b_value_1.setNum)
        self.verticalSlider_b_2.valueChanged['int'].connect(self.label_b_value_2.setNum)
        self.verticalSlider_b_3.valueChanged['int'].connect(self.label_b_value_3.setNum)
        self.verticalSlider_b_4.valueChanged['int'].connect(self.label_b_value_4.setNum)
        self.verticalSlider_b_5.valueChanged['int'].connect(self.label_b_value_5.setNum)
        self.verticalSlider_b_6.valueChanged['int'].connect(self.label_b_value_6.setNum)
        self.verticalSlider_b_7.valueChanged['int'].connect(self.label_b_value_7.setNum)
        self.verticalSlider_b_8.valueChanged['int'].connect(self.label_b_value_8.setNum)
        self.verticalSlider_b_9.valueChanged['int'].connect(self.label_b_value_9.setNum)
        self.verticalSlider_b_10.valueChanged['int'].connect(self.label_b_value_10.setNum)
        self.verticalSlider_b_11.valueChanged['int'].connect(self.label_b_value_11.setNum)
        self.verticalSlider_b_12.valueChanged['int'].connect(self.label_b_value_12.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "A"))
        self.label_a_1.setText(_translate("MainWindow", "1"))
        self.label_a_2.setText(_translate("MainWindow", "2"))
        self.label_a_3.setText(_translate("MainWindow", "3"))
        self.label_a_4.setText(_translate("MainWindow", "4"))
        self.label_a_5.setText(_translate("MainWindow", "5"))
        self.label_a_6.setText(_translate("MainWindow", "6"))
        self.label_a_7.setText(_translate("MainWindow", "7"))
        self.label_a_8.setText(_translate("MainWindow", "8"))
        self.label_a_9.setText(_translate("MainWindow", "9"))
        self.label_a_10.setText(_translate("MainWindow", "10"))
        self.label_a_11.setText(_translate("MainWindow", "11"))
        self.label_a_12.setText(_translate("MainWindow", "12"))
        self.label_a_value_1.setText(_translate("MainWindow", "0"))
        self.label_a_value_2.setText(_translate("MainWindow", "0"))
        self.label_a_value_3.setText(_translate("MainWindow", "0"))
        self.label_a_value_4.setText(_translate("MainWindow", "0"))
        self.label_a_value_5.setText(_translate("MainWindow", "0"))
        self.label_a_value_6.setText(_translate("MainWindow", "0"))
        self.label_a_value_7.setText(_translate("MainWindow", "0"))
        self.label_a_value_8.setText(_translate("MainWindow", "0"))
        self.label_a_value_9.setText(_translate("MainWindow", "0"))
        self.label_a_value_10.setText(_translate("MainWindow", "0"))
        self.label_a_value_11.setText(_translate("MainWindow", "0"))
        self.label_a_value_12.setText(_translate("MainWindow", "0"))
        self.groupBox_2.setTitle(_translate("MainWindow", "B"))
        self.label_b_1.setText(_translate("MainWindow", "1"))
        self.label_b_value_1.setText(_translate("MainWindow", "0"))
        self.label_b_value_2.setText(_translate("MainWindow", "0"))
        self.label_b_2.setText(_translate("MainWindow", "2"))
        self.label_b_value_3.setText(_translate("MainWindow", "0"))
        self.label_b_3.setText(_translate("MainWindow", "3"))
        self.label_b_value_4.setText(_translate("MainWindow", "0"))
        self.label_b_4.setText(_translate("MainWindow", "4"))
        self.label_b_value_5.setText(_translate("MainWindow", "0"))
        self.label_b_5.setText(_translate("MainWindow", "5"))
        self.label_b_value_6.setText(_translate("MainWindow", "0"))
        self.label_b_6.setText(_translate("MainWindow", "6"))
        self.label_b_value_7.setText(_translate("MainWindow", "0"))
        self.label_b_7.setText(_translate("MainWindow", "7"))
        self.label_b_value_8.setText(_translate("MainWindow", "0"))
        self.label_b_8.setText(_translate("MainWindow", "8"))
        self.label_b_value_9.setText(_translate("MainWindow", "0"))
        self.label_b_9.setText(_translate("MainWindow", "9"))
        self.label_b_value_10.setText(_translate("MainWindow", "0"))
        self.label_b_10.setText(_translate("MainWindow", "10"))
        self.label_b_value_11.setText(_translate("MainWindow", "0"))
        self.label_b_11.setText(_translate("MainWindow", "11"))
        self.label_b_value_12.setText(_translate("MainWindow", "0"))
        self.label_b_12.setText(_translate("MainWindow", "12"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Key Flash"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Sequencer"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "1"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_s_xfade.setText(_translate("MainWindow", "Fade Time"))
        self.doubleSpinBox_fadetime.setSuffix(_translate("MainWindow", " s"))
        self.doubleSpinBox_holdtime.setSuffix(_translate("MainWindow", " s"))
        self.label_s_hold.setText(_translate("MainWindow", "Hold Time"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Main"))
        self.label_main_sequencerplay.setText(_translate("MainWindow", "Run Sequencer"))
        self.label_main_sequencerstep.setText(_translate("MainWindow", "Next Step"))

